version: "3.8"

services:
  app:
    build: .
    ports:
      - "10000:10000"
    env_file: .env
    depends_on:
      - mongodb
      - redis
    networks:
      - game-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - game-network

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - game-network

networks:
  game-network:
    driver: bridge

volumes:
  mongo_data:
