import random

PARAGRAPHS = [
    
    """Deep in the heart of the ancient forest, sunlight filters through the dense canopy in shimmering pillars of gold. The air is thick with the scent of damp earth and pine needles, and the only sound is the rhythmic chirping of hidden birds. Legends speak of a forgotten city buried beneath the roots of the oldest trees, a place where time stands still and the secrets of the earth are guarded by shadows. Explorers have searched for centuries, but the forest is a shifting maze that only reveals its heart to those who do not seek it for greed or glory. To walk these paths is to acknowledge the vast, silent power of nature.""",
    """Beyond the last wooden fence of the village stretches a meadow that rolls into forest and then into hills the color of sleeping lions. Children once raced there with kites stitched from old cloth, believing the wind carried secret maps. In the twilight, foxes step lightly through tall grass, and owls claim their silent watchtowers. The trees seem to breathe with a patient rhythm, as if guarding stories too tender to shout. To wander there is to feel both small and cherished, as though the land remembers every laugh ever spilled upon it.""",
    """High above the wandering clouds, where the mountains pierce the sky like ancient spears, a lone climber pauses upon a narrow ridge. Snow drifts in silver spirals around his boots, and below him the valleys sleep beneath rivers of mist. The peaks whisper stories of those who dared before him, of ropes snapping in storms and friendships forged in thin air. Every summit is less a conquest and more a conversation with stone, a reminder that the earth is older, sterner, and infinitely patient with the small beating hearts that climb its spine.""",
    """My name is Elias, a man from the cold northern hills where the fog clings to the trees. I was raised to understand the earth not by books, but by the feel of the soil and the slope of the ridge. I believe I was meant to map the unknown. My partner is a quiet soul who spends his nights tracing the movement of the stars. He might have been a scholar, but he chose the open wilderness instead. Now we cross a vast, grey ocean toward a distant shore. He trusts the high heavens, and I trust the steady ground beneath my feet. Together, we will discover new lands and draw maps that will lead the world to wonderful places.""",
    """Rain streaks the windows of the small club as the city falls into a damp, quiet night. Deep in the alleyway, you find a small stage where a band plays the kind of jazz that feels like a heartbeat. The room is mostly empty, but the music is vibrant and alive. The guitarist plays with a tired grace, while the pianist keeps a steady, rolling rhythm on keys that have seen better days. A few teenagers loiter in the back, waiting for a rebellious sound, but the band doesn't mind. They aren't playing for the crowd or the fame. They play because the melody is the only thing that makes sense.""",
    """The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees of the garden, there came through the open door the heavy scent of the lilac, or the more delicate perfume of the pink-flowering thorn. From the corner of the divan of Persian saddle-bags on which he was lying, smoking, as was his custom, innumerable cigarettes, Lord Henry Wotton could just catch the gleam of the honey-sweet and honey-coloured blossoms of a laburnum, whose tremulous branches seemed hardly able to bear the burden of a beauty so flamelike as theirs; and now and then the fantastic shadows.""",
    """To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name. In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler. All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind. He was, I take it, the most perfect reasoning and observing machine that the world has seen, but as a lover he would have placed himself in a false position. He never spoke of the softer passions, save with a gibe and a sneer.""",
    """Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; then, I account it high time to get to sea as soon as I can. This is my substitute for pistol and ball.""",
    """A lone rider paused on a dark ridge as a storm began to brew in the west. Suddenly, the clouds tore open, revealing a terrifying sight. A massive herd of cattle with eyes of fire thundered across the heavens, their hooves striking the wind like hammers on an anvil. Behind them rode shadowy figures on pale horses, crying out in a language of thunder and rain. They were cursed to chase that burning herd forever, never catching their prey and never finding rest. One of the riders looked down and pointed a cold finger, a silent warning to the man below to change his ways before the sky claimed him.""",
    """How often have I said to you that when you have eliminated the impossible, whatever remains, however improbable, must be the truth? We know she did not come through the door, the window, or the chimney. We also know that she could not have been concealed in the room, as there is no concealment possible. Whence, then, did she come? You will not apply my precept," said Sherlock Holmes, shaking his head. "To the untrained eye, there is no hope of a solution, but to the man of science, the clues are as clear as the daylight. Now, let us look for the footprints of the intruder.""",
    """The strength of his handshake was so great that I could not repress a grimace. His hand was as cold as ice; it seemed more like the hand of a dead man than a living one. "Welcome to my house! Enter freely and of your own will!" He made no motion of stepping forward, but stood like a statue, as though his gesture of welcome had fixed him into stone. The moment I stepped over the threshold, he moved impulsively forward and took my arm. I felt his thin, strong fingers grip me like a vice. There was a strange smell in the air, a scent of old earth and something sharp like iron.""",




]

def get_random_paragraph():
    return random.choice(PARAGRAPHS)
